// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud_dotnet.Data;

#nullable disable

namespace crud_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220919180409_popular-curso")]
    partial class popularcurso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("crud_dotnet.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Back End",
                            Name = "Dotnet API"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Front End",
                            Name = "Angular"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
